Highlight-Text "[CHEATMODE] " "Blue"
Highlight-Text "vim : nvim     # " "Blue"
Highlight-Text "ll  : ls       # " "Blue"
Highlight-Text "grep: findstr  # " "Blue"
Highlight-Text "tig : tig      # " "Blue"
Highlight-Text "less: less     # " "Blue"
Highlight-Text "..  : cd..     # " "Blue"
Highlight-Text "vi  : nvim     # " "Blue"
Write-host
Highlight-Text "[TOOLS] " "Red"
Highlight-Text "ex    : exitFn        # exit " "Red"
Highlight-Text "flush : flushdns      # flushDNS " "Red"
Highlight-Text "touch : touchFn       # crete file $name " "Red"
Highlight-Text "v     : nvimFN        # nvim " "Red"
Highlight-Text "c     : cdFN          # cd && ls " "Red"
Highlight-Text "dev   : devFN         # z dev " "Red"
Highlight-Text "e     : eFN           # explorer arg " "Red"
Highlight-Text "n     : nFN           # npm run dev " "Red"
Highlight-Text "ta    : tFN           # <script src=https://cdn.tailwindcss.com></script> " "Red"
Highlight-Text "tai   : taiFN         # >> tailwind.config.js " "Red"
Highlight-Text "co    : coFN          # code . " "Red"
Highlight-Text "nrd   : nrdFN         # npm run dev " "Red"
Highlight-Text "pass  : passg         # pasword generate " "Red"
Highlight-Text "p     : pnpmRunDevFn  # pnpm run dev " "Red"
Highlight-Text "miduco: miducoFN      # miduco " "Red"
Highlight-Text "ppa   : ppathFN       # copy pwd to clip # " "Red"
Highlight-Text "pal   : palFN         # print aliases # " "Red"
Highlight-Text "rmf   : palPS1fn      # remove force param # " "Red"
Write-host
Highlight-Text "[MIDUCO]" "White"
Highlight-Text "gmidu : gmiduco       # execute miduco commit in powershell " "DarkCyan"
Write-host
Highlight-Text "[GIT]" "White"
Highlight-Text "g     : git                  # comado git" "Cyan"
Highlight-Text "gs    : gist                 # git status" "Cyan"
Highlight-Text "ga.   : gitaddDot            # git add ." "Cyan"
Highlight-Text "ga    : gitaddspread         # git add many files directories" "Cyan"
Highlight-Text "grsurl: grsurlFN             # git remote set-url origin param" "Cyan"
Highlight-Text "gpof  : gpofFN               # git push --set-upstream origin main" "Cyan"
Highlight-Text "gco   : gcme                 # git commit --amend param" "Cyan"
Highlight-Text "ginit : gitInit              # git init" "Cyan"
Highlight-Text "gll   : gitll                # git log" "Cyan"
Highlight-Text "gpob  : gpobFN               # git push --set-upstream origin param" "Cyan"
Highlight-Text "gdiff : gdiffFN              # git diff --color-words" "Cyan"
Highlight-Text "gcoa  : gcoaFN               # git commit --amend param" "Cyan"
Highlight-Text "gpush : gitPushFn            # git push" "Cyan"
Highlight-Text "gllt  : gitLogHistTakuyaFn   # git log by takuya" "Cyan"
Highlight-Text "gllf  : gitLogTakuyaFn       # git status files edits" "Cyan"
Highlight-Text "gpusht: gitPushTakuyaFn      # git push" "Cyan"
Highlight-Text "open  : gitOPENTakuyaFn      # open repo in navegator" "Cyan"
Write-host
Highlight-Text "[VIM OPEN FILES]" "White"
Highlight-Text "vimp : vimPackageFN       # vim ./.package.json " "DarkMagenta"
Highlight-Text "vimr : vimReadmeFN        # vim ./.README.MD " "DarkMagenta"
Highlight-Text "vimg : vimIgnoreFN        # vim ./.gitignore " "DarkMagenta"
Highlight-Text "vimi : vimIndexFN         # vim ./.index.js " "DarkMagenta"
Highlight-Text "vimw : vimWebpackFN       # vim ./.webpack.config.js " "DarkMagenta"
Highlight-Text "vime : vimEditorconfigFN  # vim ./.editorconfig " "DarkMagenta"
Highlight-Text "vimt : vimTsconfigFN      # vim ./.tsconfig.js " "DarkMagenta"
Highlight-Text "vimu : vimUserProfileFN   # vim ./user_profile.ps1 " "DarkMagenta"
Write-host
Highlight-Text "[ENV:VARIABLES]" "White"
Highlight-Text '#setVar : setEnvVar        # setVar $nombre $value' "White"
Write-host
Write-host "[EXAMPLES]" "White"
Highlight-Text " Create .gitignore file using this command: " "White"
Highlight-Text " welc > .gitignore " "White"
Write-host
Highlight-Text "welc   : welcFn        # welc > .gitignore" "Red"
Highlight-Text "cheat  : cheatFn       # print cheatmodes" "Red"
Highlight-Text "cheatM : cheatmodes    # print cheatmodes" "Red"
